[package]
name = "zarza_etc"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
ordered-float = { version = "4.6", features = ["serde"] }
yaml-rust = "0.4"
serde_yaml = "0.9"
